#!/bin/bash
# GOKIL Reverse Engineering - Quick Start

echo "=========================================="
echo "GOKIL REVERSE ENGINEERING TOOLKIT"
echo "=========================================="
echo ""
echo "Tools Available:"
echo "  1. JADX - Java decompiler"
echo "  2. APKTool - APK unpacker"
echo "  3. Ghidra - Native analysis"
echo "  4. Frida - Runtime hooking"
echo "  5. ADB - Android debugging"
echo "  6. Python Analyzer - Automated"
echo ""
echo "Quick Commands:"
echo "  Auto analyze: python python_tools/encrypted_apk_analyzer.py app.apk"
echo "  Decompile: jadx -d output app.apk"
echo "  Unpack: java -jar /f/apk_modding_system/decompile/apktool.jar d app.apk"
echo "  Hook: frida -U -f com.app -l hooks.js"
echo "  Debug: adb/platform-tools/adb.exe logcat"
echo ""
echo "Documentation: GOKIL_TOOLKIT_COMPLETE.txt"
echo "=========================================="
