#!/bin/bash
# YONDA Agent - Android APK Quick Builder
# Usage: bash build_apk.sh "App Name" "com.package.name" "App Description"

APP_NAME="${1:-Generated App}"
PACKAGE="${2:-com.yonda.generated}"
DESCRIPTION="${3:-Generated by YONDA Agent}"
TIMESTAMP=$(date +%s)
PROJECT=/f/android_build_system/workspace/build_$TIMESTAMP
OUTPUT_APK="/f/android_build_system/output/${APP_NAME// /_}.apk"

export ANDROID_HOME=/f/android_build_system
export PATH=$ANDROID_HOME/build-tools/35.0.0:$ANDROID_HOME/sdk/build-tools/34.0.0:$ANDROID_HOME/sdk/platform-tools:$PATH

echo "========================================"
echo "YONDA Agent - APK Builder"
echo "========================================"
echo "App Name: $APP_NAME"
echo "Package: $PACKAGE"
echo "Output: $OUTPUT_APK"
echo "========================================"

# Create project structure
mkdir -p $PROJECT/src/com/yonda/app
mkdir -p $PROJECT/res/{layout,values,drawable,mipmap-hdpi,mipmap-mdpi,mipmap-xhdpi}
cd $PROJECT

# Generate AndroidManifest.xml
cat > AndroidManifest.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="$PACKAGE"
    android:versionCode="1"
    android:versionName="1.0">
    
    <uses-sdk
        android:minSdkVersion="24"
        android:targetSdkVersion="35" />
    
    <uses-permission android:name="android.permission.INTERNET" />
    
    <application
        android:label="@string/app_name"
        android:icon="@mipmap/ic_launcher"
        android:theme="@android:style/Theme.Material.Light">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
EOF

# Generate MainActivity.java
PACKAGE_PATH=$(echo $PACKAGE | tr '.' '/')
mkdir -p src/$PACKAGE_PATH
cat > src/$PACKAGE_PATH/MainActivity.java << EOF
package $PACKAGE;

import android.app.Activity;
import android.os.Bundle;
import android.widget.*;
import android.view.ViewGroup;
import android.graphics.Color;

public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        
        LinearLayout layout = new LinearLayout(this);
        layout.setOrientation(LinearLayout.VERTICAL);
        layout.setBackgroundColor(Color.WHITE);
        layout.setPadding(50, 50, 50, 50);
        
        TextView title = new TextView(this);
        title.setText("$APP_NAME");
        title.setTextSize(28);
        title.setTextColor(Color.BLACK);
        title.setPadding(0, 0, 0, 30);
        layout.addView(title);
        
        TextView desc = new TextView(this);
        desc.setText("$DESCRIPTION");
        desc.setTextSize(16);
        desc.setTextColor(Color.GRAY);
        layout.addView(desc);
        
        setContentView(layout);
    }
}
EOF

# Generate resources
cat > res/values/strings.xml << EOF
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">$APP_NAME</string>
</resources>
EOF

# Simple launcher icon (placeholder)
echo "Creating placeholder icons..."
# Icons will be added later, APK will work without them

echo "[1/7] Compiling resources..."
aapt2 compile --dir res -o compiled.zip 2>&1 | tail -3

echo "[2/7] Linking resources..."
aapt2 link -o base.apk \
  -I $ANDROID_HOME/platforms/android-34/android.jar \
  --manifest AndroidManifest.xml \
  compiled.zip \
  --java gen 2>&1 | tail -3

echo "[3/7] Compiling Java code..."
javac -d obj \
  -classpath $ANDROID_HOME/platforms/android-34/android.jar \
  -sourcepath src \
  src/$PACKAGE_PATH/*.java \
  gen/$PACKAGE_PATH/R.java 2>&1 | tail -3

echo "[4/7] Converting to DEX..."
d8 --lib $ANDROID_HOME/platforms/android-34/android.jar \
  --output . \
  obj/$PACKAGE_PATH/*.class 2>&1 | tail -3

echo "[5/7] Packaging APK..."
cd $PROJECT
cp base.apk temp.apk
cd $PROJECT
zip -j temp.apk classes.dex 2>&1 | grep -v "adding:"

echo "[6/7] Aligning APK..."
zipalign -f 4 temp.apk aligned.apk 2>&1 | tail -3

echo "[7/7] Signing APK..."
apksigner sign \
  --ks /f/android_build_system/keystore/debug.keystore \
  --ks-pass pass:android \
  --key-pass pass:android \
  --out "$OUTPUT_APK" \
  aligned.apk 2>&1 | tail -3

# Verify
echo ""
echo "========================================"
echo "Verifying APK..."
apksigner verify --verbose "$OUTPUT_APK" 2>&1 | head -5

echo ""
echo "APK Info:"
aapt dump badging "$OUTPUT_APK" 2>&1 | grep -E "package:|sdkVersion:|targetSdkVersion:" | head -3

echo ""
echo "========================================"
echo "✅ SUCCESS!"
echo "APK: $OUTPUT_APK"
ls -lh "$OUTPUT_APK"
echo "========================================"
